src/spokanetech/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("handyhelpers/", include("handyhelpers.urls")),
    path("accounts/", include("allauth.urls")),
    path("", include("web.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]

src/web/urls.py
from django.urls import path, re_path

from web import views

app_name = "web"

urlpatterns = [
    path("", views.GetIndexContent.as_view(), name="index"),
    path("index", views.GetIndexContent.as_view(), name="index"),
    path("about", views.GetAboutContent.as_view(), name="about"),
    path("calendar/<int:year>/<int:month>", views.EventCalendarView.as_view(), name="event_calendar"),
    path("events/add", views.CreateEvent.as_view(), name="add_event"),
    path("events/<int:pk>", views.GetTechEvent.as_view(), name="get_event"),
    path("events/<int:pk>/details", views.GetTechEventModal.as_view(), name="techevent_modal"),
    path("events/<int:pk>/edit", views.UpdateEvent.as_view(), name="update_event"),
    re_path("^events/(?P<display>\w+)?$", views.GetTechEvents.as_view(), name="get_events"),
    path("techgroups/add", views.CreateTechGroup.as_view(), name="add_tech_group"),
    path("techgroups/<int:pk>", views.GetTechGroup.as_view(), name="get_techgroup"),
    path("techgroups/<int:pk>/details", views.GetTechGroupModal.as_view(), name="techgroup_modal"),
    re_path("^techgroups/(?P<display>\w+)?$", views.GetTechGroups.as_view(), name="get_techgroups"),
]

src/web/templates/web/partials/marquee/event_cards.htm
{% if queryset %}
{% for row in queryset %}
<div class="itemRight card"
    hx-get="{% url 'web:techevent_modal' row.pk %}"
    hx-target="#modal_wrapper"
    data-bs-toggle="modal"
    data-bs-target="#modal_wrapper"
>{{ row.name }}</div>
{% endfor %}
{% else %}
<div class="empty-queryset">
    No events currently scheduled
</div>
{% endif %}

src/web/templates/web/partials/marquee/group_cards.htm
{% for row in queryset %}
<div class="itemLeft card"
    hx-get="{% url 'web:techgroup_modal' row.pk %}"
    hx-target="#modal_wrapper"
    data-bs-toggle="modal"
    data-bs-target="#modal_wrapper"
>{{ row.name }}</div>

{% endfor %}