src/spokanetech/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("handyhelpers/", include("handyhelpers.urls")),
    path("accounts/", include("allauth.urls")),
    path("", include("web.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]

src/web/urls.py
from django.urls import path, re_path

from web import views

app_name = "web"

urlpatterns = [
    path("", views.GetIndexContent.as_view(), name="index"),
    path("index", views.GetIndexContent.as_view(), name="index"),
    path("about", views.GetAboutContent.as_view(), name="about"),
    path("calendar/<int:year>/<int:month>", views.EventCalendarView.as_view(), name="event_calendar"),
    path("events/add", views.CreateEvent.as_view(), name="add_event"),
    path("events/<int:pk>", views.GetTechEvent.as_view(), name="get_event"),
    path("events/<int:pk>/details", views.GetTechEventModal.as_view(), name="techevent_modal"),
    path("events/<int:pk>/edit", views.UpdateEvent.as_view(), name="update_event"),
    re_path("^events/(?P<display>\w+)?$", views.GetTechEvents.as_view(), name="get_events"),
    path("techgroups/add", views.CreateTechGroup.as_view(), name="add_tech_group"),
    path("techgroups/<int:pk>", views.GetTechGroup.as_view(), name="get_techgroup"),
    path("techgroups/<int:pk>/details", views.GetTechGroupModal.as_view(), name="techgroup_modal"),
    re_path("^techgroups/(?P<display>\w+)?$", views.GetTechGroups.as_view(), name="get_techgroups"),
]

src/templates/spokanetech/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'spokanetech/img/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'spokanetech/img/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'spokanetech/img/favicon-16x16.png' %}">
    <title>Spokane Tech</title>
    <link href="{% static 'node_modules/bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'node_modules/@fortawesome/fontawesome-free/css/all.min.css' %}" rel="stylesheet">
    
    <link rel="stylesheet" href="{% static 'spokanetech/css/index-styles.css' %}">

    <link rel="stylesheet" href="{% static 'node_modules/tippy.js/dist/tippy.css' %}">
    <link rel="stylesheet" href="{% static 'node_modules/fun-effects/src/css/fades.css' %}">
    <link rel="stylesheet" href="{% static 'node_modules/fun-effects/src/css/marquee.css' %}">
    <link rel="stylesheet" href="{% static 'node_modules/fun-effects/src/css/blur_group.css' %}">
    <link rel="stylesheet" href="{% static 'node_modules/fun-effects/src/css/background_icons.css' %}">
    
    <script type="text/javascript" src="{% static 'node_modules/htmx.org/dist/htmx.min.js' %}"></script>


</head>
<body>
    <header class="fade-in-blur" style="--fade-duration: .75s;">
        <nav class="navbar">
            <div class="logo">
                <a href="" title="SpokaneTech.org home" hx-get="{% url 'web:index' %}" hx-target="#body_main" hx-push-url="true">Home</a>
            </div>
            
            <ul class="menu">
                <li><a href="https://discord.gg/wHrSJNgpnP" target="_blank" class="tippy-tooltip" data-tippy-content="Join us on Discord"><i class="fa-brands fa-discord"></i></a></li>
                <li><a href="" hx-get="{% url 'web:get_techgroups' display='list' %}" hx-target="#body_main" hx-push-url="true" class="tippy-tooltip" data-tippy-content="View our tech groups">
                    <i class="fa-solid fa-user-group"></i></a>
                </li>
                <li><a href="" hx-get="{% url 'web:get_events' display='list' %}" hx-target="#body_main" hx-push-url="true" class="tippy-tooltip" data-tippy-content="List upcoming events">
                    <i class="fa-solid fa-list-check"></i></a>
                </li>
                <li><a hx-get="{% url 'web:event_calendar' year=0 month=0 %}" hx-target="#body_main" hx-push-url="true" class="tippy-tooltip" data-tippy-content="Calendar of events">
                  <i class="fa-solid fa-calendar-days"></i></a>
                </li>
                <li><a href="" class="tippy-tooltip" data-tippy-content="Log in or sign up">
                    <i class="fa-solid fa-right-to-bracket"></i></a>
                </li>
            </ul>
        </nav>
    </header>
 
    {% block main_content %}
    <main id="body_main" hx-get="{% url 'web:about' %}" hx-trigger="load"> 
    </main>
    {% endblock main_content %}
 
    <footer class="fade-in-blur" style="--fade-duration: .75s;">
        <p class="title">SpokaneTech.org</p>
        <p class="copyright">&copy; 2024 spokantech.org. All rights reserved.</p>
    </footer>

    {% block modals %}
    {% if not disable_modals_in_base %}
    {% include 'handyhelpers/htmx/bs5/generic_modal.htm' %}
    {% endif %}
    {% endblock modals %}
    <script type="text/javascript" src="{% static 'node_modules/jquery/dist/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'node_modules/@popperjs/core/dist/umd/popper.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'node_modules/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'node_modules/tippy.js/dist/tippy-bundle.umd.js' %}"></script>
    <script type="text/javascript" src="{% static 'node_modules/fun-effects/dist/js/marquee.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'node_modules/fun-effects/dist/js/background_icons.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'node_modules/tippy.js/dist/tippy-bundle.umd.min.js' %}"></script>

    <script>   
        // Listen for the htmx:afterOnLoad event
        document.addEventListener('htmx:afterOnLoad', function(event) {
          addAnimationDelay();
          setRightProperty();
          setLeftProperty();
          addMarqueeMouseListener();
        });
      </script>

    <!-- Initialize Tippy.js -->
    <script>
        tippy('.tippy-tooltip', {
            placement: 'bottom',
            animation: 'fade',
            arrow: true,
        });
    </script>

</body>
</html>

src/templates/spokanetech/footer.htm
<footer class="footer">
    <div class="container-fluid">
        <div class="row text-muted">
            <div class="col-6 text-start">
            </div>
            <div class="col-6 text-end">
                <ul class="list-inline">
                    <li class="list-inline-item">
                        <a href="/" class="text-muted">Spokane Tech</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>

src/templates/spokanetech/navbar.htm
<nav class="navbar navbar-expand px-3 border-bottom">
  <button class="btn" id="sidebar-toggle" type="button">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="navbar-collapse navbar">
    <ul class="navbar-nav">
      <li class="nav-item dropdown align-end mx-2">
        <a href="https://discord.gg/wHrSJNgpnP" target="_blank" title="join us on Discord!" class="nav-link"><i class="fa-brands fa-discord"></i></a>
      </li>
      <li class="nav-item dropdown align-end mx-2">
        <a href="#" class="nav-link" title="Calendar view of all events"
          hx-get="{% url 'web:event_calendar' year=0 month=0 %}" hx-target="#body_main">
          <i class="fa-regular fa-calendar-days"></i>
        </a>
      </li>
      <li class="nav-item dropdown align-end mx-2">
        <a class="nav-link" href="#" 
          hx-get="{% url 'handyhelpers:about' %}" 
          hx-target="#modal_wrapper"
          data-bs-toggle="modal"
          data-bs-target="#modal_wrapper"
        >
            <i class="fa fa-info-circle fw"></i>
        </a>
      </li>
      <li class="nav-item dropdown align-end mx-2">
        <a href="#" class="nav-link theme-toggle">
          <i class="fa-regular fa-moon"></i>
          <i class="fa-regular fa-sun"></i>
        </a>
      </li>
      <li class="nav-item mx-2">
        <a href="#" class="nav-link" title="Trigger scraping events"
          hx-post="{% url 'web:scrape' %}"
          hx-swap="none"
          hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'
          htmx:afterRequest
        >
          <i class="fa-solid fa-arrows-rotate"></i>
        </a>
      </li>
    </ul>
  </div>
</nav>

src/templates/spokanetech/sidebar.htm
<aside id="sidebar" class="js-sidebar">
    <!-- Content For Sidebar -->
    <div class="h-100">
        <div class="sidebar-logo">
            <a href="/" class="fw-bold text-primary fs-3">Spokane Tech</a>
        </div>
        <div id="sidebar-item-wrapper" hx-get="{% url 'web:build_sidebar' %}" hx-trigger="load" hx-swap="innerHTML"></div>
    </div>
</aside>